/**:
  ros__parameters:
    # weight files
    encoder_onnx_path: "/tum_models/lidar_centerpoint/pts_voxel_encoder_centerpoint.onnx"
    encoder_engine_path: "/tum_models/lidar_centerpoint/pts_voxel_encoder_centerpoint.engine"
    head_onnx_path: "/tum_models/lidar_centerpoint/pts_backbone_neck_head_centerpoint.onnx"
    head_engine_path: "/tum_models/lidar_centerpoint/pts_backbone_neck_head_centerpoint.engine"
    trt_precision: fp32
    cloud_capacity: 2000000
    post_process_params:
      # post-process params
      circle_nms_dist_threshold: 0.5
      iou_nms_target_class_names: ["CAR"]
      iou_nms_search_distance_2d: 10.0
      iou_nms_threshold: 0.1
      score_threshold: 0.35
      yaw_norm_thresholds: [0.3, 0.3, 0.3, 0.3, 0.0]
    densification_params:
      world_frame_id: world
      num_past_frames: 0
